version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: deps
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: deps
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
